services:
  dev-goraebap-blog:
    image: dev-goraebap-blog:${APP_VERSION:-latest}
    container_name: dev-goraebap-blog
    ports:
      - "8005:8080"
    volumes:
      # GitHub Secret으로 생성되는 파일 마운트
      - ./src/main/resources/application-prod.properties:/app/BOOT-INF/classes/application-prod.properties
      # 로그 파일 볼륨 마운트
      - ./logs:/app/logs
      # Credentials (Google Vision, Firebase)
      - ./.config:/app/.config:ro
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    restart: unless-stopped
    networks:
      - my-network

networks:
  my-network:
    name: my-network
    external: true
